////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin Canada Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2021 Garmin International, Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.67Release
// Tag = production/akw/21.67.00-0-gd790f76b
////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class FitMessages {

    final List<FileIdMesg> fileIdMesgs = new ArrayList<>();
    final List<FileCreatorMesg> fileCreatorMesgs = new ArrayList<>();
    final List<TimestampCorrelationMesg> timestampCorrelationMesgs = new ArrayList<>();
    final List<SoftwareMesg> softwareMesgs = new ArrayList<>();
    final List<SlaveDeviceMesg> slaveDeviceMesgs = new ArrayList<>();
    final List<CapabilitiesMesg> capabilitiesMesgs = new ArrayList<>();
    final List<FileCapabilitiesMesg> fileCapabilitiesMesgs = new ArrayList<>();
    final List<MesgCapabilitiesMesg> mesgCapabilitiesMesgs = new ArrayList<>();
    final List<FieldCapabilitiesMesg> fieldCapabilitiesMesgs = new ArrayList<>();
    final List<DeviceSettingsMesg> deviceSettingsMesgs = new ArrayList<>();
    final List<UserProfileMesg> userProfileMesgs = new ArrayList<>();
    final List<HrmProfileMesg> hrmProfileMesgs = new ArrayList<>();
    final List<SdmProfileMesg> sdmProfileMesgs = new ArrayList<>();
    final List<BikeProfileMesg> bikeProfileMesgs = new ArrayList<>();
    final List<ConnectivityMesg> connectivityMesgs = new ArrayList<>();
    final List<WatchfaceSettingsMesg> watchfaceSettingsMesgs = new ArrayList<>();
    final List<OhrSettingsMesg> ohrSettingsMesgs = new ArrayList<>();
    final List<ZonesTargetMesg> zonesTargetMesgs = new ArrayList<>();
    final List<SportMesg> sportMesgs = new ArrayList<>();
    final List<HrZoneMesg> hrZoneMesgs = new ArrayList<>();
    final List<SpeedZoneMesg> speedZoneMesgs = new ArrayList<>();
    final List<CadenceZoneMesg> cadenceZoneMesgs = new ArrayList<>();
    final List<PowerZoneMesg> powerZoneMesgs = new ArrayList<>();
    final List<MetZoneMesg> metZoneMesgs = new ArrayList<>();
    final List<DiveSettingsMesg> diveSettingsMesgs = new ArrayList<>();
    final List<DiveAlarmMesg> diveAlarmMesgs = new ArrayList<>();
    final List<DiveGasMesg> diveGasMesgs = new ArrayList<>();
    final List<GoalMesg> goalMesgs = new ArrayList<>();
    final List<ActivityMesg> activityMesgs = new ArrayList<>();
    final List<SessionMesg> sessionMesgs = new ArrayList<>();
    final List<LapMesg> lapMesgs = new ArrayList<>();
    final List<LengthMesg> lengthMesgs = new ArrayList<>();
    final List<RecordMesg> recordMesgs = new ArrayList<>();
    final List<EventMesg> eventMesgs = new ArrayList<>();
    final List<DeviceInfoMesg> deviceInfoMesgs = new ArrayList<>();
    final List<TrainingFileMesg> trainingFileMesgs = new ArrayList<>();
    final List<WeatherConditionsMesg> weatherConditionsMesgs = new ArrayList<>();
    final List<WeatherAlertMesg> weatherAlertMesgs = new ArrayList<>();
    final List<GpsMetadataMesg> gpsMetadataMesgs = new ArrayList<>();
    final List<CameraEventMesg> cameraEventMesgs = new ArrayList<>();
    final List<GyroscopeDataMesg> gyroscopeDataMesgs = new ArrayList<>();
    final List<AccelerometerDataMesg> accelerometerDataMesgs = new ArrayList<>();
    final List<MagnetometerDataMesg> magnetometerDataMesgs = new ArrayList<>();
    final List<BarometerDataMesg> barometerDataMesgs = new ArrayList<>();
    final List<ThreeDSensorCalibrationMesg> threeDSensorCalibrationMesgs = new ArrayList<>();
    final List<OneDSensorCalibrationMesg> oneDSensorCalibrationMesgs = new ArrayList<>();
    final List<VideoFrameMesg> videoFrameMesgs = new ArrayList<>();
    final List<ObdiiDataMesg> obdiiDataMesgs = new ArrayList<>();
    final List<NmeaSentenceMesg> nmeaSentenceMesgs = new ArrayList<>();
    final List<AviationAttitudeMesg> aviationAttitudeMesgs = new ArrayList<>();
    final List<VideoMesg> videoMesgs = new ArrayList<>();
    final List<VideoTitleMesg> videoTitleMesgs = new ArrayList<>();
    final List<VideoDescriptionMesg> videoDescriptionMesgs = new ArrayList<>();
    final List<VideoClipMesg> videoClipMesgs = new ArrayList<>();
    final List<SetMesg> setMesgs = new ArrayList<>();
    final List<JumpMesg> jumpMesgs = new ArrayList<>();
    final List<ClimbProMesg> climbProMesgs = new ArrayList<>();
    final List<FieldDescriptionMesg> fieldDescriptionMesgs = new ArrayList<>();
    final List<DeveloperDataIdMesg> developerDataIdMesgs = new ArrayList<>();
    final List<CourseMesg> courseMesgs = new ArrayList<>();
    final List<CoursePointMesg> coursePointMesgs = new ArrayList<>();
    final List<SegmentIdMesg> segmentIdMesgs = new ArrayList<>();
    final List<SegmentLeaderboardEntryMesg> segmentLeaderboardEntryMesgs = new ArrayList<>();
    final List<SegmentPointMesg> segmentPointMesgs = new ArrayList<>();
    final List<SegmentLapMesg> segmentLapMesgs = new ArrayList<>();
    final List<SegmentFileMesg> segmentFileMesgs = new ArrayList<>();
    final List<WorkoutMesg> workoutMesgs = new ArrayList<>();
    final List<WorkoutSessionMesg> workoutSessionMesgs = new ArrayList<>();
    final List<WorkoutStepMesg> workoutStepMesgs = new ArrayList<>();
    final List<ExerciseTitleMesg> exerciseTitleMesgs = new ArrayList<>();
    final List<ScheduleMesg> scheduleMesgs = new ArrayList<>();
    final List<TotalsMesg> totalsMesgs = new ArrayList<>();
    final List<WeightScaleMesg> weightScaleMesgs = new ArrayList<>();
    final List<BloodPressureMesg> bloodPressureMesgs = new ArrayList<>();
    final List<MonitoringInfoMesg> monitoringInfoMesgs = new ArrayList<>();
    final List<MonitoringMesg> monitoringMesgs = new ArrayList<>();
    final List<HrMesg> hrMesgs = new ArrayList<>();
    final List<StressLevelMesg> stressLevelMesgs = new ArrayList<>();
    final List<MemoGlobMesg> memoGlobMesgs = new ArrayList<>();
    final List<AntChannelIdMesg> antChannelIdMesgs = new ArrayList<>();
    final List<AntRxMesg> antRxMesgs = new ArrayList<>();
    final List<AntTxMesg> antTxMesgs = new ArrayList<>();
    final List<ExdScreenConfigurationMesg> exdScreenConfigurationMesgs = new ArrayList<>();
    final List<ExdDataFieldConfigurationMesg> exdDataFieldConfigurationMesgs = new ArrayList<>();
    final List<ExdDataConceptConfigurationMesg> exdDataConceptConfigurationMesgs = new ArrayList<>();
    final List<DiveSummaryMesg> diveSummaryMesgs = new ArrayList<>();
    final List<HrvMesg> hrvMesgs = new ArrayList<>();
    final List<PadMesg> padMesgs = new ArrayList<>();

    public FitMessages() {
    }

    public List<FileIdMesg> getFileIdMesgs() {
        return Collections.unmodifiableList(fileIdMesgs);
    }

    public List<FileCreatorMesg> getFileCreatorMesgs() {
        return Collections.unmodifiableList(fileCreatorMesgs);
    }

    public List<TimestampCorrelationMesg> getTimestampCorrelationMesgs() {
        return Collections.unmodifiableList(timestampCorrelationMesgs);
    }

    public List<SoftwareMesg> getSoftwareMesgs() {
        return Collections.unmodifiableList(softwareMesgs);
    }

    public List<SlaveDeviceMesg> getSlaveDeviceMesgs() {
        return Collections.unmodifiableList(slaveDeviceMesgs);
    }

    public List<CapabilitiesMesg> getCapabilitiesMesgs() {
        return Collections.unmodifiableList(capabilitiesMesgs);
    }

    public List<FileCapabilitiesMesg> getFileCapabilitiesMesgs() {
        return Collections.unmodifiableList(fileCapabilitiesMesgs);
    }

    public List<MesgCapabilitiesMesg> getMesgCapabilitiesMesgs() {
        return Collections.unmodifiableList(mesgCapabilitiesMesgs);
    }

    public List<FieldCapabilitiesMesg> getFieldCapabilitiesMesgs() {
        return Collections.unmodifiableList(fieldCapabilitiesMesgs);
    }

    public List<DeviceSettingsMesg> getDeviceSettingsMesgs() {
        return Collections.unmodifiableList(deviceSettingsMesgs);
    }

    public List<UserProfileMesg> getUserProfileMesgs() {
        return Collections.unmodifiableList(userProfileMesgs);
    }

    public List<HrmProfileMesg> getHrmProfileMesgs() {
        return Collections.unmodifiableList(hrmProfileMesgs);
    }

    public List<SdmProfileMesg> getSdmProfileMesgs() {
        return Collections.unmodifiableList(sdmProfileMesgs);
    }

    public List<BikeProfileMesg> getBikeProfileMesgs() {
        return Collections.unmodifiableList(bikeProfileMesgs);
    }

    public List<ConnectivityMesg> getConnectivityMesgs() {
        return Collections.unmodifiableList(connectivityMesgs);
    }

    public List<WatchfaceSettingsMesg> getWatchfaceSettingsMesgs() {
        return Collections.unmodifiableList(watchfaceSettingsMesgs);
    }

    public List<OhrSettingsMesg> getOhrSettingsMesgs() {
        return Collections.unmodifiableList(ohrSettingsMesgs);
    }

    public List<ZonesTargetMesg> getZonesTargetMesgs() {
        return Collections.unmodifiableList(zonesTargetMesgs);
    }

    public List<SportMesg> getSportMesgs() {
        return Collections.unmodifiableList(sportMesgs);
    }

    public List<HrZoneMesg> getHrZoneMesgs() {
        return Collections.unmodifiableList(hrZoneMesgs);
    }

    public List<SpeedZoneMesg> getSpeedZoneMesgs() {
        return Collections.unmodifiableList(speedZoneMesgs);
    }

    public List<CadenceZoneMesg> getCadenceZoneMesgs() {
        return Collections.unmodifiableList(cadenceZoneMesgs);
    }

    public List<PowerZoneMesg> getPowerZoneMesgs() {
        return Collections.unmodifiableList(powerZoneMesgs);
    }

    public List<MetZoneMesg> getMetZoneMesgs() {
        return Collections.unmodifiableList(metZoneMesgs);
    }

    public List<DiveSettingsMesg> getDiveSettingsMesgs() {
        return Collections.unmodifiableList(diveSettingsMesgs);
    }

    public List<DiveAlarmMesg> getDiveAlarmMesgs() {
        return Collections.unmodifiableList(diveAlarmMesgs);
    }

    public List<DiveGasMesg> getDiveGasMesgs() {
        return Collections.unmodifiableList(diveGasMesgs);
    }

    public List<GoalMesg> getGoalMesgs() {
        return Collections.unmodifiableList(goalMesgs);
    }

    public List<ActivityMesg> getActivityMesgs() {
        return Collections.unmodifiableList(activityMesgs);
    }

    public List<SessionMesg> getSessionMesgs() {
        return Collections.unmodifiableList(sessionMesgs);
    }

    public List<LapMesg> getLapMesgs() {
        return Collections.unmodifiableList(lapMesgs);
    }

    public List<LengthMesg> getLengthMesgs() {
        return Collections.unmodifiableList(lengthMesgs);
    }

    public List<RecordMesg> getRecordMesgs() {
        return Collections.unmodifiableList(recordMesgs);
    }

    public List<EventMesg> getEventMesgs() {
        return Collections.unmodifiableList(eventMesgs);
    }

    public List<DeviceInfoMesg> getDeviceInfoMesgs() {
        return Collections.unmodifiableList(deviceInfoMesgs);
    }

    public List<TrainingFileMesg> getTrainingFileMesgs() {
        return Collections.unmodifiableList(trainingFileMesgs);
    }

    public List<WeatherConditionsMesg> getWeatherConditionsMesgs() {
        return Collections.unmodifiableList(weatherConditionsMesgs);
    }

    public List<WeatherAlertMesg> getWeatherAlertMesgs() {
        return Collections.unmodifiableList(weatherAlertMesgs);
    }

    public List<GpsMetadataMesg> getGpsMetadataMesgs() {
        return Collections.unmodifiableList(gpsMetadataMesgs);
    }

    public List<CameraEventMesg> getCameraEventMesgs() {
        return Collections.unmodifiableList(cameraEventMesgs);
    }

    public List<GyroscopeDataMesg> getGyroscopeDataMesgs() {
        return Collections.unmodifiableList(gyroscopeDataMesgs);
    }

    public List<AccelerometerDataMesg> getAccelerometerDataMesgs() {
        return Collections.unmodifiableList(accelerometerDataMesgs);
    }

    public List<MagnetometerDataMesg> getMagnetometerDataMesgs() {
        return Collections.unmodifiableList(magnetometerDataMesgs);
    }

    public List<BarometerDataMesg> getBarometerDataMesgs() {
        return Collections.unmodifiableList(barometerDataMesgs);
    }

    public List<ThreeDSensorCalibrationMesg> getThreeDSensorCalibrationMesgs() {
        return Collections.unmodifiableList(threeDSensorCalibrationMesgs);
    }

    public List<OneDSensorCalibrationMesg> getOneDSensorCalibrationMesgs() {
        return Collections.unmodifiableList(oneDSensorCalibrationMesgs);
    }

    public List<VideoFrameMesg> getVideoFrameMesgs() {
        return Collections.unmodifiableList(videoFrameMesgs);
    }

    public List<ObdiiDataMesg> getObdiiDataMesgs() {
        return Collections.unmodifiableList(obdiiDataMesgs);
    }

    public List<NmeaSentenceMesg> getNmeaSentenceMesgs() {
        return Collections.unmodifiableList(nmeaSentenceMesgs);
    }

    public List<AviationAttitudeMesg> getAviationAttitudeMesgs() {
        return Collections.unmodifiableList(aviationAttitudeMesgs);
    }

    public List<VideoMesg> getVideoMesgs() {
        return Collections.unmodifiableList(videoMesgs);
    }

    public List<VideoTitleMesg> getVideoTitleMesgs() {
        return Collections.unmodifiableList(videoTitleMesgs);
    }

    public List<VideoDescriptionMesg> getVideoDescriptionMesgs() {
        return Collections.unmodifiableList(videoDescriptionMesgs);
    }

    public List<VideoClipMesg> getVideoClipMesgs() {
        return Collections.unmodifiableList(videoClipMesgs);
    }

    public List<SetMesg> getSetMesgs() {
        return Collections.unmodifiableList(setMesgs);
    }

    public List<JumpMesg> getJumpMesgs() {
        return Collections.unmodifiableList(jumpMesgs);
    }

    public List<ClimbProMesg> getClimbProMesgs() {
        return Collections.unmodifiableList(climbProMesgs);
    }

    public List<FieldDescriptionMesg> getFieldDescriptionMesgs() {
        return Collections.unmodifiableList(fieldDescriptionMesgs);
    }

    public List<DeveloperDataIdMesg> getDeveloperDataIdMesgs() {
        return Collections.unmodifiableList(developerDataIdMesgs);
    }

    public List<CourseMesg> getCourseMesgs() {
        return Collections.unmodifiableList(courseMesgs);
    }

    public List<CoursePointMesg> getCoursePointMesgs() {
        return Collections.unmodifiableList(coursePointMesgs);
    }

    public List<SegmentIdMesg> getSegmentIdMesgs() {
        return Collections.unmodifiableList(segmentIdMesgs);
    }

    public List<SegmentLeaderboardEntryMesg> getSegmentLeaderboardEntryMesgs() {
        return Collections.unmodifiableList(segmentLeaderboardEntryMesgs);
    }

    public List<SegmentPointMesg> getSegmentPointMesgs() {
        return Collections.unmodifiableList(segmentPointMesgs);
    }

    public List<SegmentLapMesg> getSegmentLapMesgs() {
        return Collections.unmodifiableList(segmentLapMesgs);
    }

    public List<SegmentFileMesg> getSegmentFileMesgs() {
        return Collections.unmodifiableList(segmentFileMesgs);
    }

    public List<WorkoutMesg> getWorkoutMesgs() {
        return Collections.unmodifiableList(workoutMesgs);
    }

    public List<WorkoutSessionMesg> getWorkoutSessionMesgs() {
        return Collections.unmodifiableList(workoutSessionMesgs);
    }

    public List<WorkoutStepMesg> getWorkoutStepMesgs() {
        return Collections.unmodifiableList(workoutStepMesgs);
    }

    public List<ExerciseTitleMesg> getExerciseTitleMesgs() {
        return Collections.unmodifiableList(exerciseTitleMesgs);
    }

    public List<ScheduleMesg> getScheduleMesgs() {
        return Collections.unmodifiableList(scheduleMesgs);
    }

    public List<TotalsMesg> getTotalsMesgs() {
        return Collections.unmodifiableList(totalsMesgs);
    }

    public List<WeightScaleMesg> getWeightScaleMesgs() {
        return Collections.unmodifiableList(weightScaleMesgs);
    }

    public List<BloodPressureMesg> getBloodPressureMesgs() {
        return Collections.unmodifiableList(bloodPressureMesgs);
    }

    public List<MonitoringInfoMesg> getMonitoringInfoMesgs() {
        return Collections.unmodifiableList(monitoringInfoMesgs);
    }

    public List<MonitoringMesg> getMonitoringMesgs() {
        return Collections.unmodifiableList(monitoringMesgs);
    }

    public List<HrMesg> getHrMesgs() {
        return Collections.unmodifiableList(hrMesgs);
    }

    public List<StressLevelMesg> getStressLevelMesgs() {
        return Collections.unmodifiableList(stressLevelMesgs);
    }

    public List<MemoGlobMesg> getMemoGlobMesgs() {
        return Collections.unmodifiableList(memoGlobMesgs);
    }

    public List<AntChannelIdMesg> getAntChannelIdMesgs() {
        return Collections.unmodifiableList(antChannelIdMesgs);
    }

    public List<AntRxMesg> getAntRxMesgs() {
        return Collections.unmodifiableList(antRxMesgs);
    }

    public List<AntTxMesg> getAntTxMesgs() {
        return Collections.unmodifiableList(antTxMesgs);
    }

    public List<ExdScreenConfigurationMesg> getExdScreenConfigurationMesgs() {
        return Collections.unmodifiableList(exdScreenConfigurationMesgs);
    }

    public List<ExdDataFieldConfigurationMesg> getExdDataFieldConfigurationMesgs() {
        return Collections.unmodifiableList(exdDataFieldConfigurationMesgs);
    }

    public List<ExdDataConceptConfigurationMesg> getExdDataConceptConfigurationMesgs() {
        return Collections.unmodifiableList(exdDataConceptConfigurationMesgs);
    }

    public List<DiveSummaryMesg> getDiveSummaryMesgs() {
        return Collections.unmodifiableList(diveSummaryMesgs);
    }

    public List<HrvMesg> getHrvMesgs() {
        return Collections.unmodifiableList(hrvMesgs);
    }

    public List<PadMesg> getPadMesgs() {
        return Collections.unmodifiableList(padMesgs);
    }
}